// packages/core/editor/src/component/header/FileMenu.tsx
import {Button, Dropdown} from "antd";
import React from "react";
import MenuItem from "./MenuItem.tsx";
import {useViewer} from "../../store/useStore.ts";
import {ExporterTool} from @plum-render/three-sdk";
import {isMesh} from "three-is";

enum FileFormat {
    DRC = "DRC",
    GLB = "GLB",
    GLTF = "GLTF",
    OBJ = "OBJ",
    PLY = "PLY",
    PLY_BINARY = "PLY (BINARY)",
    STL = "STL",
    STL_BINARY = "STL (BINARY)",
    USDZ = "USDZ"
}


const FileMenu: React.FC = () => {
    const viewer = useViewer();
    const handleNew = () => {
        console.log("新建被点击");
    };

    const handleOpen = () => {
        console.log("打开被点击");
    };

    const handleSave = () => {
        console.log("保存被点击");
        viewer?.serializeScene.downJson();
    };
    const handleZipSave = () => {
        console.log("保存被点击");
        viewer?.serializeScene.downPack();
    };

    const handleImport = () => {
        console.log("导入被点击");
    };

    const handleExport = (format: FileFormat) => {
        console.log(`导出为 ${format} 格式`);
        switch (format) {
            case FileFormat.DRC: {
                const object = viewer?.editor.selector.selectObject
                if (isMesh(object)) {
                    ExporterTool.getInstance().exportDRC(object)
                }
                break;
            }
            case FileFormat.GLB: {
                const object = viewer?.scene
                if (object) {
                    ExporterTool.getInstance().exportGLB(object, {
                        binary: true,
                    })
                }
                break;
            }
            case FileFormat.GLTF: {
                const object = viewer?.scene
                if (object) {
                    ExporterTool.getInstance().exportGLB(object)
                }
                break;
            }
            case FileFormat.OBJ: {
                const object = viewer?.scene
                if (object) {
                    ExporterTool.getInstance().exportOBJ(object)
                }
                break;
            }
            case FileFormat.PLY: {
                const object = viewer?.scene
                if (object) {
                    ExporterTool.getInstance().exportPLY(object)
                }
                break;
            }
            case FileFormat.PLY_BINARY: {
                const object = viewer?.scene
                if (object) {
                    ExporterTool.getInstance().exportPLY(object, {
                        binary: true,
                    })
                }
                break;
            }
            case FileFormat.STL: {
                const object = viewer?.scene
                if (object) {
                    ExporterTool.getInstance().exportSTL(object)
                }
                break;
            }
            case FileFormat.STL_BINARY: {
                const object = viewer?.scene
                if (object) {
                    ExporterTool.getInstance().exportSTL(object, {
                        binary: true,
                    })
                }
                break;
            }
            case FileFormat.USDZ: {
                const object = viewer?.scene
                if (object) {
                    ExporterTool.getInstance().exportUSDZ(object)
                }
                break;
            }
        }
    };

    const items = [
        {
            key: '新建',
            label: (
                <MenuItem name={'新建'} hotKey={'Ctrl N'} onClick={handleNew}/>
            )
        },
        {
            key: '打开',
            label: (
                <MenuItem name={'打开'} hotKey={'Ctrl O'} onClick={handleOpen}/>
            )
        },
        {
            key: '保存',
            label: (
                <MenuItem name={'保存'} onClick={handleSave}/>
            ),
            children: [
                {
                    key: '原生',
                    label: (
                        <MenuItem name={'原生'} onClick={handleSave}/>
                    )
                },
                {
                    key: '压缩',
                    label: (
                        <MenuItem name={'压缩'} onClick={handleZipSave}/>
                    )
                },
            ]
        },
        {
            key: '导入',
            label: (
                <MenuItem name={'导入'} onClick={handleImport}/>
            )
        },
        {
            key: '导出',
            label: '导出',
            children: Object.values(FileFormat).map(format => ({
                key: format,
                label: (
                    <MenuItem name={format} onClick={() => handleExport(format)}/>
                )
            }))
        }
    ];

    return (
        <Dropdown
            trigger={["click"]}
            menu={{items}}
            overlayClassName={'plum-menu-dropDown'}
            placement="bottomLeft"
        >
            <Button type="text">文件</Button>
        </Dropdown>
    );
}

export default FileMenu;

// packages/core/editor/src/layout/header/FileMenu.vue
<script lang="ts" setup>
import {Button as TButton, Dropdown as TDropdown, type DropdownProps, MessagePlugin} from 'tdesign-vue-next';

import {useBus} from "../../hooks";
import {ChunkSerialize, ExporterTool} from "@plum-render/three-sdk";
import {isMesh} from "three-is";

const bus = useBus();

enum FileFormat {
  DRC = "DRC",
  GLB = "GLB",
  GLTF = "GLTF",
  OBJ = "OBJ",
  PLY = "PLY",
  PLY_BINARY = "PLY (BINARY)",
  STL = "STL",
  STL_BINARY = "STL (BINARY)",
  USDZ = "USDZ"
}

const options: DropdownProps['options'] = [
  {
    content: '保存',
    value: 1,
  },
  {
    content: '导出场景包',
    value: 2,
    children: [
      {
        content: '原生',
        value: 5,
      },
      {
        content: '压缩',
        value: 6,
      },
      {
        content: '分包',
        value: 6,
      },
    ],
  },
  {
    content: '导出模型',
    value: '导出模型',
    children: [
      {content: FileFormat.DRC, value: FileFormat.DRC},
      {content: FileFormat.GLB, value: FileFormat.GLB},
      {content: FileFormat.GLTF, value: FileFormat.GLTF},
      {content: FileFormat.OBJ, value: FileFormat.OBJ},
      {content: FileFormat.PLY, value: FileFormat.PLY},
      {content: FileFormat.PLY_BINARY, value: FileFormat.PLY_BINARY},
      {content: FileFormat.STL, value: FileFormat.STL},
      {content: FileFormat.STL_BINARY, value: FileFormat.STL_BINARY},
      {content: FileFormat.USDZ, value: FileFormat.USDZ}
    ]
  }
];
const clickHandler: DropdownProps['onClick'] = (data) => {
  MessagePlugin.success(`选中【${data.content}】`);

  const viewer = bus.viewer;
  const exporterTool = ExporterTool.getInstance();
  switch (data.content) {
    case "保存": {
      const viewer = bus.viewer;
      if (!viewer) return
      const chunkSerialize = new ChunkSerialize({viewer});
      chunkSerialize.pack();
      break;
    }
    case "原生": {
      break;
    }
    case "压缩": {
      break;
    }
    case "分包": {
      break;
    }
    case FileFormat.DRC: {
      const object = viewer?.editor.selector.selectObject
      if (isMesh(object)) {
        exporterTool.exportDRC(object)
      }
      break;
    }
    case FileFormat.GLB: {
      const object = viewer?.scene
      if (object) {
        exporterTool.exportGLB(object, {
          binary: true,
        })
      }
      break;
    }
    case FileFormat.GLTF: {
      const object = viewer?.scene
      if (object) {
        exporterTool.exportGLB(object)
      }
      break;
    }
    case FileFormat.OBJ: {
      const object = viewer?.scene
      if (object) {
        exporterTool.exportOBJ(object)
      }
      break;
    }
    case FileFormat.PLY: {
      const object = viewer?.scene
      if (object) {
        exporterTool.exportPLY(object)
      }
      break;
    }
    case FileFormat.PLY_BINARY: {
      const object = viewer?.scene
      if (object) {
        exporterTool.exportPLY(object, {
          binary: true,
        })
      }
      break;
    }
    case FileFormat.STL: {
      const object = viewer?.scene
      if (object) {
        exporterTool.exportSTL(object)
      }
      break;
    }
    case FileFormat.STL_BINARY: {
      const object = viewer?.scene
      if (object) {
        exporterTool.exportSTL(object, {
          binary: true,
        })
      }
      break;
    }
    case FileFormat.USDZ: {
      const object = viewer?.scene
      if (object) {
        exporterTool.exportUSDZ(object)
      }
      break;
    }
  }


};

</script>


<template>
  <t-dropdown :max-column-width="120" :options="options" @click="clickHandler">
    <t-button variant="text">
      文件
    </t-button>
  </t-dropdown>
</template>

<style scoped>
.example-showcase .el-dropdown-link {
  cursor: pointer;
  color: var(--el-color-primary);
  display: flex;
  align-items: center;
}
</style>
