// packages/core/editor/src/component/SidePane/SidePane.tsx
import React, {Fragment, useEffect, useMemo, useState} from "react";
import {useViewer} from "../../store/useStore.ts";
import {Popover} from "antd/lib/index";
import {FloatButton, Form} from "antd";
import {InputNumberItem, ObjectAttributeProvider} from "@plum-render/common-ui";
import {CameraOutlined} from "@ant-design/icons";

const SidePane: React.FC = () => {
    const viewer = useViewer()

    useEffect(() => {
    }, [viewer])
    //------------------- 相机表单-----------------
    const [cameraForm] = Form.useForm();
    const cameraOnFieldsChange = (changedFields, allFields) => {
        const changedField = changedFields[0];
        const names = changedField.name;
        const value = changedField.value;
        // console.log(name,value)
        if (cameraControls) {
            Reflect.set(camera, names, value);
            camera.updateProjectionMatrix();
        }
    }
    let camera = useMemo(() => {
        if (viewer) {
            return viewer.threeCameraControls.camera;
        }
        return null;
    }, [viewer])
    const CameraForm = () => {
        return (
            <Form
                form={cameraForm}
                onFieldsChange={cameraOnFieldsChange}
                name="controlsForm"
                labelAlign="right"
            >
                <ObjectAttributeProvider value={{object:camera}}>
                    <InputNumberItem itemProps={{label: "视野", name: "fov"}}/>
                    <InputNumberItem itemProps={{label: "近裁剪平面", name: "near"}}/>
                    <InputNumberItem itemProps={{label: "远裁剪平面", name: "far"}}/>
                </ObjectAttributeProvider>
            </Form>
        )
    }
    //------------------- 相机表单-----------------


    //------------------- 控制器表单-----------------
    const [controlsForm] = Form.useForm();
    const ControlsOnFieldsChange = (changedFields, allFields) => {
        const changedField = changedFields[0];
        const names = changedField.name;
        const value = changedField.value;
        // console.log(name,value)
        if (cameraControls) {
            Reflect.set(cameraControls, names, value);
        }
    }
    let cameraControls = useMemo(() => {
        if (viewer) {
            return viewer.threeCameraControls.cameraControls;
        }
        return null;
    }, [viewer])

    // 视野
    const ControlsForm = () => {
        return (
            <Form
                form={controlsForm}
                onFieldsChange={ControlsOnFieldsChange}
                name="controlsForm"
                labelAlign="right"
            >
                <ObjectAttributeProvider value={{object:cameraControls}}>
                    <InputNumberItem itemProps={{label: "最小距离", name: "minDistance"}}/>
                    <InputNumberItem itemProps={{label: "最大距离", name: "maxDistance"}}/>
                    <InputNumberItem itemProps={{label: "最小旋转", name: "minAzimuthAngle"}}/>
                    <InputNumberItem itemProps={{label: "最大旋转", name: "maxAzimuthAngle"}}/>
                    <InputNumberItem itemProps={{label: "最小俯仰", name: "minPolarAngle"}}/>
                    <InputNumberItem itemProps={{label: "最大俯仰", name: "maxPolarAngle"}}/>
                </ObjectAttributeProvider>
            </Form>
        )
    }
    //------------------- 控制器表单-----------------
    const PopoverContent = () => {
        return (
            <Fragment>
                <CameraForm/>
                <ControlsForm/>
            </Fragment>
        )
    }

    const [open, setOpen] = useState(true);
    const hide = () => {
        setOpen(false);
    };
    const handleOpenChange = (newOpen: boolean) => {
        setOpen(newOpen);
    };
    return (
        <Fragment>
            <Popover content={PopoverContent}
                     title="相机设置"
                     onOpenChange={handleOpenChange}
            >
                <FloatButton icon={<CameraOutlined/>} style={{position: "absolute", top: 20, right: 20}}
                             onClick={() => {
                                 console.log('onClick')
                             }}/>
            </Popover>
        </Fragment>
    )
}

export default SidePane;

// packages/core/veditor/src/layout/sceneView/SidePane.vue
<script lang="ts" setup>
import {reactive} from "vue";
import {ElButton, ElForm, ElPopover} from "element-plus";
import {useBus} from "../../hooks";
import {InputNumberItem} from "../../common-ui";
import * as THREE from "three";
import {set} from "lodash-es";

const bus = useBus();
const form = reactive({
  fov: 75, // 默认视场角（Field of View）
  near: 0.1, // 最近可视距离
  far: 1000, // 最远可视距离
  minDistance: 1, // 最小距离
  maxDistance: 100, // 最大距离
  minAzimuthAngle: -Infinity, // 最小方位角
  maxAzimuthAngle: Infinity, // 最大方位角
  minPolarAngle: 0, // 最小极角
  maxPolarAngle: Math.PI / 2 // 最大极角
})

bus.viewerInitSubject.subscribe(() => {
  const viewer = bus.viewer;
})

const threeToUi = () => {
  const viewer = bus.viewer;
  if (!viewer) return
  const cameraControls = viewer.threeCameraControls.cameraControls;
  const camera = viewer.threeCameraControls.cameraControls.camera as THREE.PerspectiveCamera;

  form.fov = camera.fov;
  form.near = camera.near;
  form.far = camera.far;

  form.minDistance = cameraControls.minDistance;
  form.maxDistance = cameraControls.maxDistance;
  form.minAzimuthAngle = cameraControls.minAzimuthAngle;
  form.maxAzimuthAngle = cameraControls.maxAzimuthAngle;
  form.minPolarAngle = cameraControls.minPolarAngle;
  form.maxPolarAngle = cameraControls.maxPolarAngle;
}

bus.objectAttributeChangeSubject.subscribe((editValue) => {
  console.log(editValue)
  const {name, value} = editValue;

  const viewer = bus.viewer;
  if (!viewer) return
  const cameraControls = viewer.threeCameraControls.cameraControls;
  const camera = viewer.threeCameraControls.cameraControls.camera as THREE.PerspectiveCamera;

  const isCamera = ["fov", "near", "far"].includes(name as string)
  if (isCamera) {
    set(camera, name, value);
  } else {
    const isCameraControls = ["minDistance", "maxDistance", "minAzimuthAngle", "maxAzimuthAngle", "minPolarAngle", "maxPolarAngle"].includes(name as string)
    if (isCameraControls) {
      set(cameraControls, name, value);
    }
  }
})

const show = () => {
  threeToUi();
}
</script>

<template>
  <el-popover
      :width="200"
      placement="bottom"
      title="Title"
      trigger="hover"
      @show="show"
  >
    <template #reference>
      <el-button class="absolute top-[20px] right-[20px]">相机设置</el-button>
    </template>
    <el-form :model="form" class="h-full" label-width="auto" size="small">
      <input-number-item label="视野" name="fov"/>
      <input-number-item label="近裁剪平面" name="near"/>
      <input-number-item label="远裁剪平面" name="far"/>

      <input-number-item label="最小距离" name="minDistance"/>
      <input-number-item label="最大距离" name="maxDistance"/>
      <input-number-item label="最小旋转" name="minAzimuthAngle"/>
      <input-number-item label="最大旋转" name="maxAzimuthAngle"/>
      <input-number-item label="最小俯仰" name="minPolarAngle"/>
      <input-number-item label="最大俯仰" name="maxPolarAngle"/>
    </el-form>
  </el-popover>
</template>

<style scoped>

</style>
