// packages/core/editor/src/layout/sceneView/Control.vue
<script lang="ts" setup>
import {ElSegmented} from 'element-plus'
import {ref} from 'vue'
import {useBus} from "../../hooks";
import Icon from "../../components/Icon.vue";

const value = ref('translate')
const options = [
  {
    value: "translate",
    icon: "icon-move",
  },
  {
    value: "rotate",
    icon: "icon-xuanzhuan",
  },
  {
    value: "scale",
    icon: 'icon-suofang',
  },
]
const bus = useBus();

const change = (val: string) => {

  const viewer = bus.viewer;
  if (viewer) {
    viewer.editor.transformControlsWarp.transformControls.setMode(val);
  }
}

</script>

<template>
  <div class="absolute top-[20px] left-[10px] z-999">
    <el-segmented v-model="value" :options="options" direction="vertical" size="small" @change="change">
      <template #default="scope">
        <icon :icon-name="scope.item.icon"/>
      </template>
    </el-segmented>
  </div>
</template>

<style scoped>

</style>

// packages/core/editor/src/component/SidePane/Control.tsx
import React, {Fragment, useEffect, useState} from "react";
import {useViewer} from "../../store/useStore.ts";
import {ArrowsAltOutlined, FullscreenOutlined, RedoOutlined} from "@ant-design/icons";
import {Segmented} from "antd";

interface IconContainerProps {
    mode: string
    $select: string
}

const Control: React.FC = () => {
    const viewer = useViewer()
    useEffect(() => {
    }, [viewer])
    const [mode, setMode] = useState("translate")

    const handleClick = (mode: string) => {
        if (viewer) {
            setMode(mode)
            viewer.editor.transformControlsWarp.transformControls.setMode(mode);
        }
    }

    return (
        <Fragment>
            <div style={{
                zIndex: 9999,
                position: "absolute",
                top: "20px",
                left: "10px",
            }}>
                <Segmented
                    vertical
                    size={'large'}
                    options={[
                        {value: 'translate', icon: <FullscreenOutlined/>},
                        {value: 'rotate', icon: <RedoOutlined/>},
                        {value: 'Kanban', icon: <ArrowsAltOutlined/>},
                    ]}
                    onChange={handleClick}

                />
            </div>
        </Fragment>
    )
}

export default Control;
